name: cmz_app
channels:
  - conda-forge
  - defaults
dependencies:
  - blinker=1.9.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2025.1.31
  - certifi=2024.12.14
  - cffi=1.17.1
  - charset-normalizer=3.4.1
  - click=8.1.8
  - dash=2.17.1
  - flask=3.1.0
  - h2=4.2.0
  - hpack=4.1.0
  - hyperframe=6.1.0
  - idna=3.10
  - importlib-metadata=8.6.1
  - itsdangerous=2.2.0
  - jinja2=3.1.5
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcxx=19.1.7
  - libffi=3.4.2
  - libgfortran=5.0.0
  - libgfortran5=13.2.0
  - liblapack=3.9.0
  - liblzma=5.6.4
  - libopenblas=0.3.28
  - libsqlite=3.48.0
  - libzlib=1.3.1
  - llvm-openmp=19.1.7
  - markupsafe=3.0.2
  - narwhals=1.25.0
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - numpy=2.2.2
  - openssl=3.4.0
  - packaging=24.2
  - pandas=2.2.3
  - pip=25.0
  - plotly=6.0.0
  - pycparser=2.22
  - pysocks=1.7.1
  - python=3.10.16
  - python-dateutil=2.9.0.post0
  - python-tzdata=2025.1
  - python_abi=3.10
  - pytz=2024.1
  - readline=8.2
  - requests=2.32.3
  - retrying=1.3.3
  - setuptools=75.8.0
  - six=1.17.0
  - tk=8.6.13
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzdata=2025a
  - urllib3=2.3.0
  - werkzeug=3.1.3
  - wheel=0.45.1
  - zipp=3.21.0
  - zstandard=0.23.0
  - zstd=1.5.6
